// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_EncapsulatedObject_2eproto__INCLUDED
#define PROTOBUF_EncapsulatedObject_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>

namespace kad {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_EncapsulatedObject_2eproto();
void protobuf_AssignDesc_EncapsulatedObject_2eproto();
void protobuf_ShutdownFile_EncapsulatedObject_2eproto();

class EncapsulatedObject;

// ===================================================================

class EncapsulatedObject : public ::google::protobuf::Message {
 public:
  EncapsulatedObject();
  virtual ~EncapsulatedObject();
  
  EncapsulatedObject(const EncapsulatedObject& from);
  
  inline EncapsulatedObject& operator=(const EncapsulatedObject& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const EncapsulatedObject& default_instance();
  void Swap(EncapsulatedObject* other);
  
  // implements Message ----------------------------------------------
  
  EncapsulatedObject* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EncapsulatedObject& from);
  void MergeFrom(const EncapsulatedObject& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  const ::google::protobuf::Descriptor* GetDescriptor() const;
  const ::google::protobuf::Reflection* GetReflection() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bytes data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  
  // required uint32 last_published_time = 2;
  inline bool has_last_published_time() const;
  inline void clear_last_published_time();
  static const int kLastPublishedTimeFieldNumber = 2;
  inline ::google::protobuf::uint32 last_published_time() const;
  inline void set_last_published_time(::google::protobuf::uint32 value);
  
  // required uint32 original_published_time = 3;
  inline bool has_original_published_time() const;
  inline void clear_original_published_time();
  static const int kOriginalPublishedTimeFieldNumber = 3;
  inline ::google::protobuf::uint32 original_published_time() const;
  inline void set_original_published_time(::google::protobuf::uint32 value);
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* data_;
  static const ::std::string _default_data_;
  ::google::protobuf::uint32 last_published_time_;
  ::google::protobuf::uint32 original_published_time_;
  friend void  protobuf_AddDesc_EncapsulatedObject_2eproto();
  friend void protobuf_AssignDesc_EncapsulatedObject_2eproto();
  friend void protobuf_ShutdownFile_EncapsulatedObject_2eproto();
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static EncapsulatedObject* default_instance_;
};
// ===================================================================


// ===================================================================


// ===================================================================

// EncapsulatedObject

// required bytes data = 1;
inline bool EncapsulatedObject::has_data() const {
  return _has_bit(0);
}
inline void EncapsulatedObject::clear_data() {
  if (data_ != &_default_data_) {
    data_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& EncapsulatedObject::data() const {
  return *data_;
}
inline void EncapsulatedObject::set_data(const ::std::string& value) {
  _set_bit(0);
  if (data_ == &_default_data_) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void EncapsulatedObject::set_data(const char* value) {
  _set_bit(0);
  if (data_ == &_default_data_) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void EncapsulatedObject::set_data(const void* value, size_t size) {
  _set_bit(0);
  if (data_ == &_default_data_) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EncapsulatedObject::mutable_data() {
  _set_bit(0);
  if (data_ == &_default_data_) {
    data_ = new ::std::string;
  }
  return data_;
}

// required uint32 last_published_time = 2;
inline bool EncapsulatedObject::has_last_published_time() const {
  return _has_bit(1);
}
inline void EncapsulatedObject::clear_last_published_time() {
  last_published_time_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 EncapsulatedObject::last_published_time() const {
  return last_published_time_;
}
inline void EncapsulatedObject::set_last_published_time(::google::protobuf::uint32 value) {
  _set_bit(1);
  last_published_time_ = value;
}

// required uint32 original_published_time = 3;
inline bool EncapsulatedObject::has_original_published_time() const {
  return _has_bit(2);
}
inline void EncapsulatedObject::clear_original_published_time() {
  original_published_time_ = 0u;
  _clear_bit(2);
}
inline ::google::protobuf::uint32 EncapsulatedObject::original_published_time() const {
  return original_published_time_;
}
inline void EncapsulatedObject::set_original_published_time(::google::protobuf::uint32 value) {
  _set_bit(2);
  original_published_time_ = value;
}


}  // namespace kad
#endif  // PROTOBUF_EncapsulatedObject_2eproto__INCLUDED
